import React from "react";
import Sidebar from "../components/Sidebar";

function Diagnostics() {
  return (
    <div>
      <Sidebar />
      <div className="ml-12">
        <h1 className="text-2xl md:text-3xl font-bold ml-5 pt-8">
          Diagnostic Trouble Code (DTC)
        </h1>
        <h2 className="text-justify text-base md:text-lg xl:text-xl">
          <span className="font-semibold">DTC</span> is a code generated by a
          vehicle&quot;s onboard diagnostic system (OBD) to indicate a specific
          problem or malfunction within the vehicle&quot;s systems.
        </h2>
        <h2 className="text-justify text-base md:text-lg xl:text-xl">
          <span className="font-semibold">If the DTC is empty,</span> it means
          your vehicle is working fine.
        </h2>
        <h2 className="text-justify text-base md:text-lg xl:text-xl">
          <span className="font-semibold">
            If the DTC is not empty, but nothing at the description,
          </span>{" "}
          it means unknown error code, probably a vehicle-specific DTC.
        </h2>
      </div>
    </div>
  );
}

export default Diagnostics;
