import Sidebar from "../components/Sidebar";

function Diagnostics() {
  return (
    <div>
      <Sidebar />
      <div className="ml-12">
        <h1 className="text-2xl md:text-3xl font-bold ml-5 sm:ml-10 pt-8">
          Diagnostic Trouble Code (DTC)
        </h1>
        <div className="mx-5 sm:mx-10">
          <h2 className="my-5 text-justify text-base md:text-lg xl:text-xl">
            <span className="font-semibold">DTC</span> is a code generated by a
            vehicle&apos;s onboard diagnostic system (OBD) to indicate a
            specific problem or malfunction within the vehicle&apos;s systems.
          </h2>
          <h2 className="text-justify text-base md:text-lg xl:text-xl">
            <span className="font-semibold">If the DTC is empty,</span> it means
            your vehicle is working fine.
          </h2>
          <h2 className="my-5 text-justify text-base md:text-lg xl:text-xl">
            <span className="font-semibold">
              If the DTC is not empty, but nothing at the description,
            </span>{" "}
            it means unknown error code, probably a vehicle-specific DTC.
          </h2>
          <table className="md:mt-10 xl:mt-20 text-[#233163] text-center text-base md:text-lg xl:text-xl m-auto">
            <thead className="border-t-2  border-b-2 border-[#233163]">
              <tr>
                <th>
                  <h1 className="text-lg md:text-xl xl:text-2xl font-semibold px-4 py-2">
                    DTC
                  </h1>
                </th>
                <th>
                  <h1 className="text-lg md:text-xl xl:text-2xl font-semibold px-4 py-2">
                    Description
                  </h1>
                </th>
              </tr>
            </thead>
            <tbody className="text-base md:text-lg xl:text-xl">
              <tr>
                <td className="px-4 py-2">P0104</td>
                <td className="px-4 py-2">
                  Mass or Volume Air Flow Circuit Intermittent
                </td>
              </tr>
              <tr>
                <td className="px-4 py-2">B0003</td>
                <td></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}

export default Diagnostics;
