export const parameterOptions = [
  { value: "c_enginerpm", label: "Engine RPM", score: 200, unit: "RPM" },
  { value: "c_vehiclespeed", label: "Vehicle Speed", score: 220, unit: "km/h" },
  {
    value: "c_throttleposition",
    label: "Throttle Position",
    score: 240,
    unit: "%",
  },
  {
    value: "c_enginecoolanttemperature",
    label: "Engine Coolant Temperature",
    score: 250,
    unit: "°C",
  },
  {
    value: "c_shorttermfueltrim",
    label: "Short Term Fuel Trim",
    score: 260,
    unit: "%",
  },
  {
    value: "c_longtermfueltrim",
    label: "Long Term Fuel Trim",
    score: 270,
    unit: "%",
  },
  {
    value: "c_intakeairtemperature",
    label: "Intake Air Temperature",
    score: 280,
    unit: "°C",
  },
  {
    value: "c_oxygensensorbank1sensor1",
    label: "Oxygen Sensor Bank 1 Sensor 1",
    score: 290,
    unit: "V",
  },
  {
    value: "c_oxygensensorbank2sensor2",
    label: "Oxygen Sensor Bank 2 Sensor 2",
    score: 300,
    unit: "V",
  },
  { value: "c_massairflow", label: "Mass Air Flow", score: 320, unit: "g/s" },
  {
    value: "c_catalysttemperature",
    label: "Catalyst Temperature",
    score: 330,
    unit: "°C",
  },
  {
    value: "c_engineoiltemperature",
    label: "Engine Oil Temperature",
    score: 350,
    unit: "°C",
  },
  {
    value: "c_intakemaniholdpressure",
    label: "Intake Manihold Pressure",
    score: 230,
    unit: "kPa",
  },
];
